
class Dim3x3:

    SIDE_LEN = 53
    #SLICE_LEN = SIDE_LEN/3

    #EFFECTOR D (DOWN)
    D_LOWER = 0
    D_HOME = 25
    D_LAYER_TOP = 40
    D_LAYER_MID = 59
    D_LAYER_ALL = 80

    #D_LAYER_TOP =D_HOME +SLICE_LEN * 1
    #D_LAYER_MID =D_HOME +SLICE_LEN * 2        
    #D_LAYER_ALL =D_HOME +SLICE_LEN * 3

    #EFFECTOR C(CLAMPING)
    C_HOME_OFFSET = 10
    C_HOME =SIDE_LEN + C_HOME_OFFSET
    C_CLAMP =SIDE_LEN - 3
    
    #EFFECTOR G (GRIPPER)
    G_OFFSET = 25
    G_HOME = SIDE_LEN + G_OFFSET
    G_GRIP = SIDE_LEN + 8

#@dataclass
class Dim2x2:

    SIDE_LEN = 53
    #SLICE_LEN = SIDE_LEN/3

    #EFFECTOR D (DOWN)
    D_LOWER = 0
    D_HOME = 25
    D_LAYER_TOP = 41
    D_LAYER_MID = 59
    D_LAYER_ALL = 80

    #D_LAYER_TOP =D_HOME +SLICE_LEN * 1
    #D_LAYER_MID =D_HOME +SLICE_LEN * 2        
    #D_LAYER_ALL =D_HOME +SLICE_LEN * 3

    #EFFECTOR C(CLAMPING)
    C_HOME_OFFSET = 10
    C_HOME =SIDE_LEN + C_HOME_OFFSET
    C_CLAMP =SIDE_LEN
    
    #EFFECTOR G (GRIPPER)
    G_OFFSET = 25
    G_HOME = SIDE_LEN + G_OFFSET
    G_GRIP = SIDE_LEN + 8


DIM_CLASSES = {2: Dim2x2, 3: Dim3x3}